"use client"
import { useEffect } from 'react';
import { Inter } from "next/font/google";
import "../styles/global.scss";
import Header from '../components/Header'
import  store  from '../../store/store'
import { Provider } from 'react-redux'
//import { logListeners } from '../../logListeners.mjs';
const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
 
    /* useEffect(() => {
      logListeners(process.stdin, 'data'); // Log listeners for 'data' event on stdin
    }, []); */
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Header/>
          {children}
        </Provider>
        
      </body>
    
    </html>
  );
}
